services:
  db:
    image: mariadb:10.7
    container_name: db
    env_file:
      - .env
    ports:
      - "3306:3306"  # Expose le port 3306 de l'hôte vers 3306 du conteneur
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: parcoursup_voeux_jp2-web
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
