services:
  db:
    image: mariadb:10.7
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${MARIADB_PORT}:${MARIADB_PORT}"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: ghcr.io/karl2301/parcoursup_voeux_jp2/web:latest
    container_name: parcoursup_voeux_jp2-web
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - app_network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["--interval", "86400", "--cleanup"]
    restart: unless-stopped
    networks:
    - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
